// Code generated by "enumer -type IDType -json"; DO NOT EDIT.

package figi

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _IDTypeName = "IDTypeUnspecifiedID_ISINID_BB_UNIQUEID_SEDOLID_COMMONID_WERTPAPIERID_CUSIPID_CINSID_BBID_BB_8_CHRID_TRACEID_ITALYID_EXCH_SYMBOLID_FULL_EXCHANGE_SYMBOLCOMPOSITE_ID_BB_GLOBALID_BB_GLOBAL_SHARE_CLASS_LEVELID_BB_GLOBALID_BB_SEC_NUM_DESTICKERBASE_TICKERID_CUSIP_8_CHROCC_SYMBOLUNIQUE_ID_FUT_OPTOPRA_SYMBOLTRADING_SYSTEM_IDENTIFIERID_SHORT_CODEVENDOR_INDEX_CODE"

var _IDTypeIndex = [...]uint16{0, 17, 24, 36, 44, 53, 66, 74, 81, 86, 97, 105, 113, 127, 150, 172, 202, 214, 231, 237, 248, 262, 272, 289, 300, 325, 338, 355}

const _IDTypeLowerName = "idtypeunspecifiedid_isinid_bb_uniqueid_sedolid_commonid_wertpapierid_cusipid_cinsid_bbid_bb_8_chrid_traceid_italyid_exch_symbolid_full_exchange_symbolcomposite_id_bb_globalid_bb_global_share_class_levelid_bb_globalid_bb_sec_num_destickerbase_tickerid_cusip_8_chrocc_symbolunique_id_fut_optopra_symboltrading_system_identifierid_short_codevendor_index_code"

func (i IDType) String() string {
	if i >= IDType(len(_IDTypeIndex)-1) {
		return fmt.Sprintf("IDType(%d)", i)
	}
	return _IDTypeName[_IDTypeIndex[i]:_IDTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _IDTypeNoOp() {
	var x [1]struct{}
	_ = x[IDTypeUnspecified-(0)]
	_ = x[ID_ISIN-(1)]
	_ = x[ID_BB_UNIQUE-(2)]
	_ = x[ID_SEDOL-(3)]
	_ = x[ID_COMMON-(4)]
	_ = x[ID_WERTPAPIER-(5)]
	_ = x[ID_CUSIP-(6)]
	_ = x[ID_CINS-(7)]
	_ = x[ID_BB-(8)]
	_ = x[ID_BB_8_CHR-(9)]
	_ = x[ID_TRACE-(10)]
	_ = x[ID_ITALY-(11)]
	_ = x[ID_EXCH_SYMBOL-(12)]
	_ = x[ID_FULL_EXCHANGE_SYMBOL-(13)]
	_ = x[COMPOSITE_ID_BB_GLOBAL-(14)]
	_ = x[ID_BB_GLOBAL_SHARE_CLASS_LEVEL-(15)]
	_ = x[ID_BB_GLOBAL-(16)]
	_ = x[ID_BB_SEC_NUM_DES-(17)]
	_ = x[TICKER-(18)]
	_ = x[BASE_TICKER-(19)]
	_ = x[ID_CUSIP_8_CHR-(20)]
	_ = x[OCC_SYMBOL-(21)]
	_ = x[UNIQUE_ID_FUT_OPT-(22)]
	_ = x[OPRA_SYMBOL-(23)]
	_ = x[TRADING_SYSTEM_IDENTIFIER-(24)]
	_ = x[ID_SHORT_CODE-(25)]
	_ = x[VENDOR_INDEX_CODE-(26)]
}

var _IDTypeValues = []IDType{IDTypeUnspecified, ID_ISIN, ID_BB_UNIQUE, ID_SEDOL, ID_COMMON, ID_WERTPAPIER, ID_CUSIP, ID_CINS, ID_BB, ID_BB_8_CHR, ID_TRACE, ID_ITALY, ID_EXCH_SYMBOL, ID_FULL_EXCHANGE_SYMBOL, COMPOSITE_ID_BB_GLOBAL, ID_BB_GLOBAL_SHARE_CLASS_LEVEL, ID_BB_GLOBAL, ID_BB_SEC_NUM_DES, TICKER, BASE_TICKER, ID_CUSIP_8_CHR, OCC_SYMBOL, UNIQUE_ID_FUT_OPT, OPRA_SYMBOL, TRADING_SYSTEM_IDENTIFIER, ID_SHORT_CODE, VENDOR_INDEX_CODE}

var _IDTypeNameToValueMap = map[string]IDType{
	_IDTypeName[0:17]:         IDTypeUnspecified,
	_IDTypeLowerName[0:17]:    IDTypeUnspecified,
	_IDTypeName[17:24]:        ID_ISIN,
	_IDTypeLowerName[17:24]:   ID_ISIN,
	_IDTypeName[24:36]:        ID_BB_UNIQUE,
	_IDTypeLowerName[24:36]:   ID_BB_UNIQUE,
	_IDTypeName[36:44]:        ID_SEDOL,
	_IDTypeLowerName[36:44]:   ID_SEDOL,
	_IDTypeName[44:53]:        ID_COMMON,
	_IDTypeLowerName[44:53]:   ID_COMMON,
	_IDTypeName[53:66]:        ID_WERTPAPIER,
	_IDTypeLowerName[53:66]:   ID_WERTPAPIER,
	_IDTypeName[66:74]:        ID_CUSIP,
	_IDTypeLowerName[66:74]:   ID_CUSIP,
	_IDTypeName[74:81]:        ID_CINS,
	_IDTypeLowerName[74:81]:   ID_CINS,
	_IDTypeName[81:86]:        ID_BB,
	_IDTypeLowerName[81:86]:   ID_BB,
	_IDTypeName[86:97]:        ID_BB_8_CHR,
	_IDTypeLowerName[86:97]:   ID_BB_8_CHR,
	_IDTypeName[97:105]:       ID_TRACE,
	_IDTypeLowerName[97:105]:  ID_TRACE,
	_IDTypeName[105:113]:      ID_ITALY,
	_IDTypeLowerName[105:113]: ID_ITALY,
	_IDTypeName[113:127]:      ID_EXCH_SYMBOL,
	_IDTypeLowerName[113:127]: ID_EXCH_SYMBOL,
	_IDTypeName[127:150]:      ID_FULL_EXCHANGE_SYMBOL,
	_IDTypeLowerName[127:150]: ID_FULL_EXCHANGE_SYMBOL,
	_IDTypeName[150:172]:      COMPOSITE_ID_BB_GLOBAL,
	_IDTypeLowerName[150:172]: COMPOSITE_ID_BB_GLOBAL,
	_IDTypeName[172:202]:      ID_BB_GLOBAL_SHARE_CLASS_LEVEL,
	_IDTypeLowerName[172:202]: ID_BB_GLOBAL_SHARE_CLASS_LEVEL,
	_IDTypeName[202:214]:      ID_BB_GLOBAL,
	_IDTypeLowerName[202:214]: ID_BB_GLOBAL,
	_IDTypeName[214:231]:      ID_BB_SEC_NUM_DES,
	_IDTypeLowerName[214:231]: ID_BB_SEC_NUM_DES,
	_IDTypeName[231:237]:      TICKER,
	_IDTypeLowerName[231:237]: TICKER,
	_IDTypeName[237:248]:      BASE_TICKER,
	_IDTypeLowerName[237:248]: BASE_TICKER,
	_IDTypeName[248:262]:      ID_CUSIP_8_CHR,
	_IDTypeLowerName[248:262]: ID_CUSIP_8_CHR,
	_IDTypeName[262:272]:      OCC_SYMBOL,
	_IDTypeLowerName[262:272]: OCC_SYMBOL,
	_IDTypeName[272:289]:      UNIQUE_ID_FUT_OPT,
	_IDTypeLowerName[272:289]: UNIQUE_ID_FUT_OPT,
	_IDTypeName[289:300]:      OPRA_SYMBOL,
	_IDTypeLowerName[289:300]: OPRA_SYMBOL,
	_IDTypeName[300:325]:      TRADING_SYSTEM_IDENTIFIER,
	_IDTypeLowerName[300:325]: TRADING_SYSTEM_IDENTIFIER,
	_IDTypeName[325:338]:      ID_SHORT_CODE,
	_IDTypeLowerName[325:338]: ID_SHORT_CODE,
	_IDTypeName[338:355]:      VENDOR_INDEX_CODE,
	_IDTypeLowerName[338:355]: VENDOR_INDEX_CODE,
}

var _IDTypeNames = []string{
	_IDTypeName[0:17],
	_IDTypeName[17:24],
	_IDTypeName[24:36],
	_IDTypeName[36:44],
	_IDTypeName[44:53],
	_IDTypeName[53:66],
	_IDTypeName[66:74],
	_IDTypeName[74:81],
	_IDTypeName[81:86],
	_IDTypeName[86:97],
	_IDTypeName[97:105],
	_IDTypeName[105:113],
	_IDTypeName[113:127],
	_IDTypeName[127:150],
	_IDTypeName[150:172],
	_IDTypeName[172:202],
	_IDTypeName[202:214],
	_IDTypeName[214:231],
	_IDTypeName[231:237],
	_IDTypeName[237:248],
	_IDTypeName[248:262],
	_IDTypeName[262:272],
	_IDTypeName[272:289],
	_IDTypeName[289:300],
	_IDTypeName[300:325],
	_IDTypeName[325:338],
	_IDTypeName[338:355],
}

// IDTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func IDTypeString(s string) (IDType, error) {
	if val, ok := _IDTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _IDTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to IDType values", s)
}

// IDTypeValues returns all values of the enum
func IDTypeValues() []IDType {
	return _IDTypeValues
}

// IDTypeStrings returns a slice of all String values of the enum
func IDTypeStrings() []string {
	strs := make([]string, len(_IDTypeNames))
	copy(strs, _IDTypeNames)
	return strs
}

// IsAIDType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i IDType) IsAIDType() bool {
	for _, v := range _IDTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for IDType
func (i IDType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for IDType
func (i *IDType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("IDType should be a string, got %s", data)
	}

	var err error
	*i, err = IDTypeString(s)
	return err
}
