// Code generated by "enumer -type IDType -json"; DO NOT EDIT.

package figi

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _IDTypeName = "ID_UNSPECIFIEDID_ISINID_BB_UNIQUEID_SEDOLID_COMMONID_WERTPAPIERID_CUSIPID_CINSID_BBID_BB_8_CHRID_TRACEID_ITALYID_EXCH_SYMBOLID_FULL_EXCHANGE_SYMBOLCOMPOSITE_ID_BB_GLOBALID_BB_GLOBAL_SHARE_CLASS_LEVELID_BB_GLOBALID_BB_SEC_NUM_DESTICKERBASE_TICKERID_CUSIP_8_CHROCC_SYMBOLUNIQUE_ID_FUT_OPTOPRA_SYMBOLTRADING_SYSTEM_IDENTIFIERID_SHORT_CODEVENDOR_INDEX_CODE"

var _IDTypeIndex = [...]uint16{0, 14, 21, 33, 41, 50, 63, 71, 78, 83, 94, 102, 110, 124, 147, 169, 199, 211, 228, 234, 245, 259, 269, 286, 297, 322, 335, 352}

const _IDTypeLowerName = "id_unspecifiedid_isinid_bb_uniqueid_sedolid_commonid_wertpapierid_cusipid_cinsid_bbid_bb_8_chrid_traceid_italyid_exch_symbolid_full_exchange_symbolcomposite_id_bb_globalid_bb_global_share_class_levelid_bb_globalid_bb_sec_num_destickerbase_tickerid_cusip_8_chrocc_symbolunique_id_fut_optopra_symboltrading_system_identifierid_short_codevendor_index_code"

func (i IDType) String() string {
	if i >= IDType(len(_IDTypeIndex)-1) {
		return fmt.Sprintf("IDType(%d)", i)
	}
	return _IDTypeName[_IDTypeIndex[i]:_IDTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _IDTypeNoOp() {
	var x [1]struct{}
	_ = x[ID_UNSPECIFIED-(0)]
	_ = x[ID_ISIN-(1)]
	_ = x[ID_BB_UNIQUE-(2)]
	_ = x[ID_SEDOL-(3)]
	_ = x[ID_COMMON-(4)]
	_ = x[ID_WERTPAPIER-(5)]
	_ = x[ID_CUSIP-(6)]
	_ = x[ID_CINS-(7)]
	_ = x[ID_BB-(8)]
	_ = x[ID_BB_8_CHR-(9)]
	_ = x[ID_TRACE-(10)]
	_ = x[ID_ITALY-(11)]
	_ = x[ID_EXCH_SYMBOL-(12)]
	_ = x[ID_FULL_EXCHANGE_SYMBOL-(13)]
	_ = x[COMPOSITE_ID_BB_GLOBAL-(14)]
	_ = x[ID_BB_GLOBAL_SHARE_CLASS_LEVEL-(15)]
	_ = x[ID_BB_GLOBAL-(16)]
	_ = x[ID_BB_SEC_NUM_DES-(17)]
	_ = x[TICKER-(18)]
	_ = x[BASE_TICKER-(19)]
	_ = x[ID_CUSIP_8_CHR-(20)]
	_ = x[OCC_SYMBOL-(21)]
	_ = x[UNIQUE_ID_FUT_OPT-(22)]
	_ = x[OPRA_SYMBOL-(23)]
	_ = x[TRADING_SYSTEM_IDENTIFIER-(24)]
	_ = x[ID_SHORT_CODE-(25)]
	_ = x[VENDOR_INDEX_CODE-(26)]
}

var _IDTypeValues = []IDType{ID_UNSPECIFIED, ID_ISIN, ID_BB_UNIQUE, ID_SEDOL, ID_COMMON, ID_WERTPAPIER, ID_CUSIP, ID_CINS, ID_BB, ID_BB_8_CHR, ID_TRACE, ID_ITALY, ID_EXCH_SYMBOL, ID_FULL_EXCHANGE_SYMBOL, COMPOSITE_ID_BB_GLOBAL, ID_BB_GLOBAL_SHARE_CLASS_LEVEL, ID_BB_GLOBAL, ID_BB_SEC_NUM_DES, TICKER, BASE_TICKER, ID_CUSIP_8_CHR, OCC_SYMBOL, UNIQUE_ID_FUT_OPT, OPRA_SYMBOL, TRADING_SYSTEM_IDENTIFIER, ID_SHORT_CODE, VENDOR_INDEX_CODE}

var _IDTypeNameToValueMap = map[string]IDType{
	_IDTypeName[0:14]:         ID_UNSPECIFIED,
	_IDTypeLowerName[0:14]:    ID_UNSPECIFIED,
	_IDTypeName[14:21]:        ID_ISIN,
	_IDTypeLowerName[14:21]:   ID_ISIN,
	_IDTypeName[21:33]:        ID_BB_UNIQUE,
	_IDTypeLowerName[21:33]:   ID_BB_UNIQUE,
	_IDTypeName[33:41]:        ID_SEDOL,
	_IDTypeLowerName[33:41]:   ID_SEDOL,
	_IDTypeName[41:50]:        ID_COMMON,
	_IDTypeLowerName[41:50]:   ID_COMMON,
	_IDTypeName[50:63]:        ID_WERTPAPIER,
	_IDTypeLowerName[50:63]:   ID_WERTPAPIER,
	_IDTypeName[63:71]:        ID_CUSIP,
	_IDTypeLowerName[63:71]:   ID_CUSIP,
	_IDTypeName[71:78]:        ID_CINS,
	_IDTypeLowerName[71:78]:   ID_CINS,
	_IDTypeName[78:83]:        ID_BB,
	_IDTypeLowerName[78:83]:   ID_BB,
	_IDTypeName[83:94]:        ID_BB_8_CHR,
	_IDTypeLowerName[83:94]:   ID_BB_8_CHR,
	_IDTypeName[94:102]:       ID_TRACE,
	_IDTypeLowerName[94:102]:  ID_TRACE,
	_IDTypeName[102:110]:      ID_ITALY,
	_IDTypeLowerName[102:110]: ID_ITALY,
	_IDTypeName[110:124]:      ID_EXCH_SYMBOL,
	_IDTypeLowerName[110:124]: ID_EXCH_SYMBOL,
	_IDTypeName[124:147]:      ID_FULL_EXCHANGE_SYMBOL,
	_IDTypeLowerName[124:147]: ID_FULL_EXCHANGE_SYMBOL,
	_IDTypeName[147:169]:      COMPOSITE_ID_BB_GLOBAL,
	_IDTypeLowerName[147:169]: COMPOSITE_ID_BB_GLOBAL,
	_IDTypeName[169:199]:      ID_BB_GLOBAL_SHARE_CLASS_LEVEL,
	_IDTypeLowerName[169:199]: ID_BB_GLOBAL_SHARE_CLASS_LEVEL,
	_IDTypeName[199:211]:      ID_BB_GLOBAL,
	_IDTypeLowerName[199:211]: ID_BB_GLOBAL,
	_IDTypeName[211:228]:      ID_BB_SEC_NUM_DES,
	_IDTypeLowerName[211:228]: ID_BB_SEC_NUM_DES,
	_IDTypeName[228:234]:      TICKER,
	_IDTypeLowerName[228:234]: TICKER,
	_IDTypeName[234:245]:      BASE_TICKER,
	_IDTypeLowerName[234:245]: BASE_TICKER,
	_IDTypeName[245:259]:      ID_CUSIP_8_CHR,
	_IDTypeLowerName[245:259]: ID_CUSIP_8_CHR,
	_IDTypeName[259:269]:      OCC_SYMBOL,
	_IDTypeLowerName[259:269]: OCC_SYMBOL,
	_IDTypeName[269:286]:      UNIQUE_ID_FUT_OPT,
	_IDTypeLowerName[269:286]: UNIQUE_ID_FUT_OPT,
	_IDTypeName[286:297]:      OPRA_SYMBOL,
	_IDTypeLowerName[286:297]: OPRA_SYMBOL,
	_IDTypeName[297:322]:      TRADING_SYSTEM_IDENTIFIER,
	_IDTypeLowerName[297:322]: TRADING_SYSTEM_IDENTIFIER,
	_IDTypeName[322:335]:      ID_SHORT_CODE,
	_IDTypeLowerName[322:335]: ID_SHORT_CODE,
	_IDTypeName[335:352]:      VENDOR_INDEX_CODE,
	_IDTypeLowerName[335:352]: VENDOR_INDEX_CODE,
}

var _IDTypeNames = []string{
	_IDTypeName[0:14],
	_IDTypeName[14:21],
	_IDTypeName[21:33],
	_IDTypeName[33:41],
	_IDTypeName[41:50],
	_IDTypeName[50:63],
	_IDTypeName[63:71],
	_IDTypeName[71:78],
	_IDTypeName[78:83],
	_IDTypeName[83:94],
	_IDTypeName[94:102],
	_IDTypeName[102:110],
	_IDTypeName[110:124],
	_IDTypeName[124:147],
	_IDTypeName[147:169],
	_IDTypeName[169:199],
	_IDTypeName[199:211],
	_IDTypeName[211:228],
	_IDTypeName[228:234],
	_IDTypeName[234:245],
	_IDTypeName[245:259],
	_IDTypeName[259:269],
	_IDTypeName[269:286],
	_IDTypeName[286:297],
	_IDTypeName[297:322],
	_IDTypeName[322:335],
	_IDTypeName[335:352],
}

// IDTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func IDTypeString(s string) (IDType, error) {
	if val, ok := _IDTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _IDTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to IDType values", s)
}

// IDTypeValues returns all values of the enum
func IDTypeValues() []IDType {
	return _IDTypeValues
}

// IDTypeStrings returns a slice of all String values of the enum
func IDTypeStrings() []string {
	strs := make([]string, len(_IDTypeNames))
	copy(strs, _IDTypeNames)
	return strs
}

// IsAIDType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i IDType) IsAIDType() bool {
	for _, v := range _IDTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for IDType
func (i IDType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for IDType
func (i *IDType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("IDType should be a string, got %s", data)
	}

	var err error
	*i, err = IDTypeString(s)
	return err
}
