// Code generated by "enumer -type OptionEnum -trimprefix OptionEnum -json"; DO NOT EDIT.

package figi

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _OptionEnumName = "UnspecifiedCallPut"

var _OptionEnumIndex = [...]uint8{0, 11, 15, 18}

const _OptionEnumLowerName = "unspecifiedcallput"

func (i OptionEnum) String() string {
	if i >= OptionEnum(len(_OptionEnumIndex)-1) {
		return fmt.Sprintf("OptionEnum(%d)", i)
	}
	return _OptionEnumName[_OptionEnumIndex[i]:_OptionEnumIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _OptionEnumNoOp() {
	var x [1]struct{}
	_ = x[OptionEnumUnspecified-(0)]
	_ = x[OptionEnumCall-(1)]
	_ = x[OptionEnumPut-(2)]
}

var _OptionEnumValues = []OptionEnum{OptionEnumUnspecified, OptionEnumCall, OptionEnumPut}

var _OptionEnumNameToValueMap = map[string]OptionEnum{
	_OptionEnumName[0:11]:       OptionEnumUnspecified,
	_OptionEnumLowerName[0:11]:  OptionEnumUnspecified,
	_OptionEnumName[11:15]:      OptionEnumCall,
	_OptionEnumLowerName[11:15]: OptionEnumCall,
	_OptionEnumName[15:18]:      OptionEnumPut,
	_OptionEnumLowerName[15:18]: OptionEnumPut,
}

var _OptionEnumNames = []string{
	_OptionEnumName[0:11],
	_OptionEnumName[11:15],
	_OptionEnumName[15:18],
}

// OptionEnumString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func OptionEnumString(s string) (OptionEnum, error) {
	if val, ok := _OptionEnumNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _OptionEnumNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to OptionEnum values", s)
}

// OptionEnumValues returns all values of the enum
func OptionEnumValues() []OptionEnum {
	return _OptionEnumValues
}

// OptionEnumStrings returns a slice of all String values of the enum
func OptionEnumStrings() []string {
	strs := make([]string, len(_OptionEnumNames))
	copy(strs, _OptionEnumNames)
	return strs
}

// IsAOptionEnum returns "true" if the value is listed in the enum definition. "false" otherwise
func (i OptionEnum) IsAOptionEnum() bool {
	for _, v := range _OptionEnumValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for OptionEnum
func (i OptionEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for OptionEnum
func (i *OptionEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("OptionEnum should be a string, got %s", data)
	}

	var err error
	*i, err = OptionEnumString(s)
	return err
}
